image: ekino/docker-buildbox:node6.10-2017.03.30

# TODO: build and deploy

stages:
  - test
#  - build
  - report

lint:
  stage: test
  tags: [ek-docker]

  script:
    - make install
    - yarn lint

test_js:
  stage: test
  tags: [ek-docker]

  script:
    - make install
    - yarn test

#build:
#  stage: build
#  tags: [ek-docker]
#
#  script:
#    - make install
#    - make build

report_failure:
  stage: report
  tags: [ek-docker]
  script:
    - ci-helper flowdock:message ekino "Autodata" "@team - Oops, the build is broken! ${CI_BUILD_REF_NAME} - https://gitlab.fullsix.com/dfo-demo/autodata/commit/${CI_BUILD_REF}/builds"
  when: on_failure